# Generated by Django 3.1.1 on 2025-07-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('RECORDS', 'Disques'), ('CLOTHING', 'Vetements'), ('POSTERS', 'Affiches'), ('MISECELLANEOUS', 'Divers'), ('TICKET', 'Ticket')], max_length=14),
        ),
    ]
