# Generated by Django 3.1.1 on 2025-07-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20250718_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
