# Generated by Django 3.1.1 on 2025-07-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
